Hubert / Small design fixes
deriv-pocs/deriv-developers-portal pull request #18
Opened 2022-01-18 12:25 UTC by hubert-deriv

2022-01-24 12:52 UTC, adam-deriv requested changes

2022-01-24 12:52 UTC, adam-deriv commented on registration_api.js
> +                                            await removeApp(event.data);;
why, removeeeve ;

2022-01-24 12:52 UTC, adam-deriv commented on registration_api.js
> +    console.log('testestestestest');
whyyyyyyyy, remove pls

2022-01-25 08:17 UTC, hubert-deriv commented on registration_api.js
> +    console.log('testestestestest');
Why, I think this looks amazing. JK.

2022-01-25 08:17 UTC, hubert-deriv commented on registration_api.js
> +                                            await removeApp(event.data);;
Fixed

2022-01-25 08:32 UTC, adam-deriv approved these changes

2022-01-25 08:33 UTC, merged