Fixed the header
deriv-pocs/deriv-developers-portal pull request #60
Opened 2022-03-21 09:41 UTC by sanjam-deriv

2022-03-21 11:43 UTC, hubert-deriv reviewed
Looks good to me! If you fix the underline issue, I will approve this, then we can push it to Ranjan to check :)

2022-03-22 07:40 UTC, adam-deriv requested changes

2022-03-22 07:40 UTC, adam-deriv commented on components/Header/Header.module.scss
> +    @media (max-width: 992px) {
replace media query with [data-state~=state.responsive....etc] just like in https://github.com/deriv-pocs/deriv-developers-portal/pull/59/files#diff-0c4f92e7b1d221127bc3e6e9839b06fbc203588b8e721d640e45b8c72db98973R126-R129

2022-03-22 07:40 UTC, adam-deriv commented on components/Header/Header.module.scss
> +           --app-registration-tab-active-underline: var(--background);
nice usage of variables

2022-03-22 10:54 UTC, adam-deriv approved these changes

2022-03-22 10:57 UTC, merged